[build]
target = "i386-baremetal.json"

rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "opt-level=z"
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]